version: "3.7"

services:
  ansible:
    container_name: ansible-controller
    build: docker/ansible
    tty: true
    working_dir: /var/data
    volumes:
      - ./ansible:/var/data
    environment:
      - ANSIBLE_CONFIG=.
    networks:
      - ansible-network

  target:
    container_name: ansible-target
    build: docker/target
    tty: true
    init: true
    networks:
      - ansible-network
    cap_add:
      - NET_ADMIN

networks:
  ansible-network:
    name: ansible_network